APP_NAME=dis-sign
SIGNING_KEY=2C4259D83B8EC4BBBA6CDCF067528B17E4558404

CATEGORIES=(
  "bin:bin/*"
  "docs:docs/*"
  "examples:examples/*"
  "test:test/*"
  "assets:assets/*"
  "root:README.md LICENSE .gitignore dis-sign.conf"
)